// File: lib/firebase_options.dart
// This file should be generated by running: flutterfire configure
// For now, this is a placeholder. Replace with actual Firebase config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe6XfU_YVHDKAztv8i5ycXyp9KLD65tPU',
    appId: '1:864585434364:web:534e7b3574ad9de5028379',
    messagingSenderId: '864585434364',
    projectId: 'fire-auth-todoapp',
    authDomain: 'fire-auth-todoapp.firebaseapp.com',
    storageBucket: 'fire-auth-todoapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACOE-jgS4jmy9mwxmVKXuvE7z9MpJCijs',
    appId: '1:864585434364:android:9d8a4503f74c3acd028379',
    messagingSenderId: '864585434364',
    projectId: 'fire-auth-todoapp',
    storageBucket: 'fire-auth-todoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMOES1tBhVBj3Je__psH9c-ArQqNY971o',
    appId: '1:306571070100:ios:fe90c30f0d86673016c281',
    messagingSenderId: '306571070100',
    projectId: 'todo-firbase-auth',
    storageBucket: 'todo-firbase-auth.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMOES1tBhVBj3Je__psH9c-ArQqNY971o',
    appId: '1:306571070100:ios:fe90c30f0d86673016c281',
    messagingSenderId: '306571070100',
    projectId: 'todo-firbase-auth',
    storageBucket: 'todo-firbase-auth.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy-9D3ZElEvZNJhz5i_2Rhk9OFRGLdxbg',
    appId: '1:306571070100:web:53b6ce37125dac8b16c281',
    messagingSenderId: '306571070100',
    projectId: 'todo-firbase-auth',
    authDomain: 'todo-firbase-auth.firebaseapp.com',
    storageBucket: 'todo-firbase-auth.firebasestorage.app',
  );

}